setw -g mode-keys vi
set -g  status-keys vi
set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 1. 允许 tmux 自动继承和更新宿主机的语言环境变量
set-option -g update-environment "LANG LC_ALL LC_CTYPE"

# 2. 强制设置默认终端支持 256 色（防止某些终端因为色彩配置导致字符显示异常）
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# 3. 兼容旧版本 tmux（如果是 tmux 2.1 或更早版本，取消下方两行的注释）
# set -g utf8 on
# set-window-option -g utf8 on
